language: python

python:
  - "3.6"
  - "3.7"

sudo: enabled

dist: xenial

# Command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Add database & Docker
services:
  - postgresql
  - docker

# Database configuration
before_script:
  - psql -c "CREATE USER musicmanager WITH ENCRYPTED PASSWORD 'testdbpw';" -U postgres
  - psql -c 'ALTER USER musicmanager CREATEDB;' -U postgres
  - psql -c 'CREATE DATABASE musicmanager OWNER musicmanager;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE musicmanager TO musicmanager;' -U postgres

# Build for master & dev branch only.
branches:
  only:
    - master
    - dev

# Command to run tests
script: coverage run --source=manager_core manage.py test -v 2 --settings=MusicManager.settings.dev

# Build and push Docker image and check coverage of all codes
after_success:
  - docker login --username $(DOCKERHUB_USERNAME) --password-stdin
  - docker build -t $(DOCKERHUB_USERNAME)/musicmanager -t $(DOCKERHUB_USERNAME)/musicmanager:$(git describe --tags) .
  - docker push $(DOCKERHUB_USERNAME)/musicmanager $(DOCKERHUB_USERNAME)/musicmanager:$(git describe --tags)
  - coveralls