language: python

python:
  - "3.6"
  - "3.7"

sudo: enabled

dist: xenial

# Command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Add databases.
#services:
#  - postgresql

# Environment variables.
#env:
#  - DATABASE_URL=postgres:///$(whoami)

# Build for master & dev branch only.
branches:
  only:
    - master
    - dev

# Command to run tests
script: coverage run --source=manager_core manage.py test -v 2 --settings=MusicManager.settings.local

after_success: coveralls