# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=200)),
                ('album_cover_file', models.CharField(max_length=200)),
                ('album_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk', models.IntegerField()),
                ('track_num', models.IntegerField()),
                ('track_title', models.CharField(max_length=200)),
                ('track_artist', models.CharField(max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_core.Album')),
            ],
        ),
    ]
