# Generated by Django 1.10.5 on 2017-02-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner_count',
            field=models.IntegerField(default=0),
        ),
    ]
