# Generated by Django 1.10.5 on 2017-03-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_core', '0003_albumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
