# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_core', '0003_auto_20161220_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='foreign_artist',
        ),
    ]
