# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_core', '0004_remove_album_foreign_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
