# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_core', '0005_auto_20170306_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover_file',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='manager_core/cover_files'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='owner_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
