# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_core', '0007_auto_20170322_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover_file',
            field=models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to='manager_core/cover_files'),
        ),
    ]
